version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: ./backend.Dockerfile
        ports:
            - 8888:80

    naxsi:
        build:
            context: .
            dockerfile: ./naxsi.Dockerfile
        depends_on:
           - backend
        volumes:
            - ./nginx/sites-available/:/etc/nginx/sites-available/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/naxsi-errors:/usr/share/nginx/html/naxsi-errors
            - ./nginx/naxsi_core.rules:/usr/share/naxsi/naxsi_core.rules
            - ./configs/key.pem:/tmp/key.pem
            - ./configs/cert.pem:/tmp/cert.pem
        ports:
            - 7777:80
            - 8443:443

    db:
        image: mysql:8.0.27
        environment:
            MYSQL_ROOT_PASSWORD: r00tp4ssw0rd
            MYSQL_DATABASE: movies_db
            MYSQL_USER: appuser
            MYSQL_PASSWORD: apppass
        volumes:
            - ./mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
        #ports:
        #    - 9906:3306
